"""
Django settings for djangoproject project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s^2zhghn4e1b07isdn4mmawz%76kn6qwe)#mvsba_vve(h2jy4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages', 
    'django.contrib.staticfiles', #подключение статических файлов
    #apps
    'film',
    'serials',
    'authentication',
    'djangoproject',
    #other
    'rest_framework.authtoken',
    'djoser',
    'django_filters',
    'corsheaders', 
    'import_export',
    'simple_history',
    'social_django',
    'drf_yasg',
    'django_celery_beat'
    # 'rest_framework_social_oauth2',
    # 'oauth2_provider'
]
#celery mailhog
CELERY_BEAT_SCHEDULE = {
    'send_daily_emails': {
        'task': 'djangoproject.tasks.send_daily_email', 
        # 'schedule': crontab(hour=8, minute=0),
        'schedule': crontab(),
        'args': ('user@example.com',),
    },
}

CELERY_BROKER_URL = 'redis://127.0.0.1:16379/0' 
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:16379/0' 
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Moscow'

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 1025
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False

#----

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'  #указание путя для статических файлов
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



SOCIAL_AUTH_VK_OAUTH2_KEY = '51948559'
SOCIAL_AUTH_VK_OAUTH2_SECRET  = 'Vz20JSgxwPPOG3vhlgRY'

SOCIAL_AUTH_GITHUB_KEY = 'Ov23li5ONJCy23gmcqZs'

SOCIAL_AUTH_GITHUB_SECRET = '2ff280048e3a00b75164523227da3f63c20fcb82'

# AUTHENTICATION_BACKENDS = (
#   'social_core.backends.vk.VKOAuth2',
#   'rest_framework_social_oauth2.backends.DjangoOAuth2',
#   'django.contrib.auth.backends.ModelBackend'
# )

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2', 
    'django.contrib.auth.backends.ModelBackend',
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        # 'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        # 'rest_framework_social_oauth2.authentication.SocialAuthentication'
     ], 
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 8,
    'DEFAULT_FILTER_BACKEND': (
      'django_filters.rest_framework.DjangoFilterBackend'
    ),
    'DEFAULT_PERMISSION_CLASSES':[
        # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
}

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:8000',
    "http://localhost:8000",
    'http://localhost:5173'
]

CORS_ORIGIN_WHITELIST = [
    'http://127.0.0.1:8000'
    "http://localhost:8000",
    'http://localhost:5173',
]

CORS_ALLOW_HEADERS = ('content-disposition', 'accept-encoding',
                      'content-type', 'accept', 'origin', 'Authorization',
                      'access-control-allow-methods')

# AUTH_USER_MODEL = 'authentication.User'

#linter 
PYLINT_RUNNER_ENABLED = True
SOCIAL_AUTH_POSTGRES_JSONFIELD = True

