# Generated by Django 4.2.5 on 2024-01-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serials', '0003_serials_director_serials_genre'),
        ('film', '0009_alter_films_rating_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('username', models.CharField(default='', max_length=20, verbose_name='username')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('favorite_films', models.ManyToManyField(related_name='понравилось', to='film.films')),
                ('favorite_serials', models.ManyToManyField(related_name='понравилось', to='serials.serials')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
