# Generated by Django 4.2.5 on 2024-01-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0010_historicalrate_historicalfilms'),
        ('serials', '0003_serials_director_serials_genre'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_films',
            field=models.ManyToManyField(blank=True, null=True, related_name='понравилось', to='film.films'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_serials',
            field=models.ManyToManyField(blank=True, null=True, related_name='понравилось', to='serials.serials'),
        ),
    ]
