# Generated by Django 4.2.5 on 2023-10-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serials',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
