# Generated by Django 4.2.5 on 2023-10-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_genre_films_genre'),
        ('serials', '0002_serials_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='serials',
            name='director',
            field=models.ManyToManyField(to='film.director', verbose_name='Режиссер'),
        ),
        migrations.AddField(
            model_name='serials',
            name='genre',
            field=models.ManyToManyField(to='film.genre', verbose_name='Жанр'),
        ),
    ]
