# Generated by Django 4.2.5 on 2023-10-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='actors',
            field=models.CharField(default='', max_length=200, verbose_name='Актеры'),
        ),
        migrations.AddField(
            model_name='films',
            name='director',
            field=models.CharField(default='', max_length=50, verbose_name='Режиссер'),
        ),
    ]
