# Generated by Django 4.2.5 on 2023-10-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_films_actors_films_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
