# Generated by Django 4.2.5 on 2023-10-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_films_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Режиссер')),
            ],
            options={
                'verbose_name': 'Режиссер',
                'verbose_name_plural': 'Режиссеры',
            },
        ),
        migrations.AddField(
            model_name='films',
            name='direct',
            field=models.ManyToManyField(to='film.director', verbose_name='Режиссер'),
        ),
    ]
