# Generated by Django 4.2.5 on 2023-10-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_director_films_direct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='director',
        ),
    ]
