# Generated by Django 4.2.5 on 2023-10-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_remove_films_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.AddField(
            model_name='films',
            name='genre',
            field=models.ManyToManyField(to='film.genre', verbose_name='Жанр'),
        ),
    ]
